### ISSUE TITLE
Unknown name provided

### ISSUE THREAD

**Issue by Anaguiros** [Lucas-C/rpg-bonhomme#2]
Message d'erreur poppant lors du rensignement d'un name="xxx" avec xxx n'existant pas en base de données.
C'est pas très joli tout ça ...
![rpg_fail](https://cloud.githubusercontent.com/assets/548821/5680332/0cda0d2c-980c-11e4-9d26-e42ce15da2e8.png)

**Comment by Lucas-C** [comment]
Bien vu.
Fixé sur le serveur, en attente de commit.
Pour l'instant j'ai juste remplacé l'alerte par un message de log. T'aurais une autre suggestion pour notifier l'utilisateur ? Je veux pas ajouter de dépence à la Notify.js

**Comment by Anaguiros** [comment]
redirection vers la page "?layout=xxx" sans l'argument name ?
Je prefere foutre des baffes aux users pour les forcer à aller où je veux

**Comment by Lucas-C** [comment]
Fixed in 6da77493baed71aa9f7045b5e43f9d2bf692953c
