### ISSUE TITLE
Ajout d'une homepage, UI ?

### ISSUE THREAD

**Issue by Anaguiros** [Lucas-C/rpg-bonhomme#3]
Ca pourrait être une idée de rajouter une homepage permettant un affichage globalisé des différents perso hébergé sur le serveur, avant une redirection vers la fiche en elle-même.

Ca permettrait de rendre tout ça un peu plus noob-proof, faire des tris (genre liste de perso par jeu), et rendre tout ça un peu plus propre (j'aime bien coller des URL forger avec mes mimines, mais bon ...).

Après ça dépends bien sur du niveau de finition souhaité sur l'ensemble.

**Comment by Lucas-C** [comment]
Entièrement d'accord dans le fond, après je pense qu'il faudra d'abord mettre en place un système de "lecture seule" des fiches de persos.
Je m'explique : actuellement, le fait que les feuilles de persos ne soit pas référencés fonctionne comme une sorte de protection évitant que n'importe quel troll bousille toutes les fiches listées sur la page d'accueil. C'est un peu le même principe pour les pads, ou les galeries et documents Google: l'absence de référencement garantit une restriction de l'accès au contenu à un cercle privé (ceux avec qui on a partagé le lien).
De plus, comme actuellement la clef pour stocker les feuilles de persos est seulement constitué du nom de perso, il y a un risque assez élevé de collisions et de trouver une feuille de perso "par hasard" (ou en brute-forçant tous les noms possibles).

En résumé:
- une page d'acceuil permettant une création de perso plus "user-friendly" et listant les layouts de feuilles de persos disponibles : OK à 100%
- on pourrait remplacer la clef utilisée pour le stockage des persos côté serveur par un ID généré aléatoirement, comme le fait [etherpad](http://etherpad.org), pour sécuriser l'architecture actuelle (au détriment d'une certaine transparence des URLs de fiche de perso) -> _discussed in #5_
- on pourrait mettre en place un système de génération d'URL en lecture-seule pour les feuilles de persos : le WSGI côté serveur pourrait générer un 2e ID, pour lequel il n'accepterait que les requêtes _GET_ -> _discussed in #5_
- on pourrait ajouter une checkbox dans le CSS pour activer/désactiver le référencement au choix. Je préférerais proposer cette option seulement pour la version "lecture-seule" des pages, ou alors afficher une tooltip prévenant des risques.

T'en penses quoi ?

**Comment by Anaguiros** [comment]
Homepage : gros boutons noob-friendly avec les jeux proposés pour une création de perso comme il faut.

Sinon j'aime bien l'idée d'implémentation discuter en #5. Genre un paramètre spécial pour la modification des feuilles "existantes, et du coup un accès lecture pour tous les autres.

**Comment by Anaguiros** [comment]
Tiens j'avais commencé à bosser sur une homepage qu'elle est jolie.
Je me garde ça dans une branche sous le coude si tu veux
![homepage](https://cloud.githubusercontent.com/assets/548821/5721507/c70572f8-9b32-11e4-9516-085e8ba44442.png)

**Comment by Lucas-C** [comment]
Superbe ! Beau boulot :)
Deux petites questions :
- t'as utilisé un framework ? Ça ressemble un peu à du bootstrap.
- les images viennent d'où ? Elles sont cool !

**Comment by Anaguiros** [comment]
Bootstrap en effet

images de dés venant d'ici (http://en.wikipedia.org/wiki/Dungeons_%26_Dragons) et la biohazard venant de google image (penser à en trouver une libre de droit pour plus tard, là c'est pour me test perso)

**Comment by Lucas-C** [comment]
Commit https://github.com/Lucas-C/rpg-bonhomme/commit/77c54d0fde187dbe4d96d7767bc5f8449b0e0c15 introduced a `/list/$prefix` REST endpoint that should facilitate this.
I'm thinking about a simple SPA home page there. More on this later

**Comment by Lucas-C** [comment]
Done ! https://chezsoi.org/lucas/jdr/rpg-bonhomme/
